/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile.$username.index'
import { Route as ProfileUsernameFollowersRouteImport } from './routes/profile.$username.followers'
import { Route as ProfileUsernameFollowingRouteImport } from './routes/profile.$username.following'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameFollowersRoute =
  ProfileUsernameFollowersRouteImport.update({
    id: '/profile/$username/followers',
    path: '/profile/$username/followers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileUsernameFollowingRoute =
  ProfileUsernameFollowingRouteImport.update({
    id: '/profile/$username/following',
    path: '/profile/$username/following',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/suggestions': typeof SuggestionsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/$username/followers': typeof ProfileUsernameFollowersRoute
  '/profile/$username/following': typeof ProfileUsernameFollowingRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/suggestions': typeof SuggestionsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/$username/followers': typeof ProfileUsernameFollowersRoute
  '/profile/$username/following': typeof ProfileUsernameFollowingRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/suggestions': typeof SuggestionsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/$username/followers': typeof ProfileUsernameFollowersRoute
  '/profile/$username/following': typeof ProfileUsernameFollowingRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/login'
    | '/logout'
    | '/register'
    | '/search'
    | '/suggestions'
    | '/profile/edit'
    | '/profile/$username/followers'
    | '/profile/$username/following'
    | '/profile/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/login'
    | '/logout'
    | '/register'
    | '/search'
    | '/suggestions'
    | '/profile/edit'
    | '/profile/$username/followers'
    | '/profile/$username/following'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/login'
    | '/logout'
    | '/register'
    | '/search'
    | '/suggestions'
    | '/profile/edit'
    | '/profile/$username/followers'
    | '/profile/$username/following'
    | '/profile/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SuggestionsRoute: typeof SuggestionsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileUsernameFollowersRoute: typeof ProfileUsernameFollowersRoute
  ProfileUsernameFollowingRoute: typeof ProfileUsernameFollowingRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/followers': {
      id: '/profile/$username/followers'
      path: '/profile/$username/followers'
      fullPath: '/profile/$username/followers'
      preLoaderRoute: typeof ProfileUsernameFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/following': {
      id: '/profile/$username/following'
      path: '/profile/$username/following'
      fullPath: '/profile/$username/following'
      preLoaderRoute: typeof ProfileUsernameFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SuggestionsRoute: SuggestionsRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileUsernameFollowersRoute: ProfileUsernameFollowersRoute,
  ProfileUsernameFollowingRoute: ProfileUsernameFollowingRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
